
version: '2'

services:
    mysql:
        build: ./mysql/
        volumes:
            - ../db:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - network_dev

    mongodb:
        build: ./mongodb/
        volumes:
            - ../mongodb:/data/db
        networks:
            - network_dev

    redis:
        build: ./redis/
        networks:
            - network_dev

    app:
        image: php:7-fpm
        volumes:
            - ../logs:/var/log/apache2/logs
            # - ./ssl:/etc/ssl
        command: "true"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        volumes:
            - ../pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        networks:
            - network_dev

    php7:
        build: ./php7/
        links:
            - mysql
            - redis
            - mongodb
        volumes_from:
            - app
        volumes:
            - ./php7/.ssh/:/root/.ssh/
            - ../projects/php7:/var/www/html
        networks:
            - network_dev
        ports:
            - "80:80"
            - "443:443"
        hostname: mwasylecki
        environment:
            DOCKER_HOST: DOCKER_HOST

    php5:
        build: ./php5/
        links:
            - mysql
            - redis
        volumes_from:
            - app
        volumes:
            - ../projects/php5:/var/www/html
        networks:
            - network_dev
        ports:
            - "81:80"
            - "444:443"
        environment:
            - DOCKER_HOST

networks:
    network_dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: '172.99.0.0/16'
                  gateway: '172.99.0.1'